/**
 * 水性ホビーカラー プリセットデータ
 */
const PRESET_AQUEOUS = {
  maker: '水性ホビーカラー',
  series: '水性ホビーカラー',
  type: 'acrylic',
  colors: [
    { colorCode: 'H-1',  colorName: 'ホワイト' },
    { colorCode: 'H-2',  colorName: 'ブラック' },
    { colorCode: 'H-3',  colorName: 'レッド' },
    { colorCode: 'H-4',  colorName: 'イエロー' },
    { colorCode: 'H-5',  colorName: 'ブルー' },
    { colorCode: 'H-6',  colorName: 'グリーン' },
    { colorCode: 'H-7',  colorName: 'オレンジ' },
    { colorCode: 'H-8',  colorName: 'シルバー' },
    { colorCode: 'H-9',  colorName: 'ゴールド' },
    { colorCode: 'H-10', colorName: 'コッパー' },
    { colorCode: 'H-11', colorName: 'ネービーブルー' },
    { colorCode: 'H-12', colorName: 'フレッシュ' },
    { colorCode: 'H-13', colorName: 'ニュートラルグレー' },
    { colorCode: 'H-14', colorName: 'オフホワイト' },
    { colorCode: 'H-15', colorName: 'ミドルストーン' },
    { colorCode: 'H-16', colorName: 'ブラックグリーン' },
    { colorCode: 'H-17', colorName: 'RLM71ダークグリーン' },
    { colorCode: 'H-18', colorName: 'RLM70ブラックグリーン' },
    { colorCode: 'H-19', colorName: 'サンドイエロー' },
    { colorCode: 'H-20', colorName: 'ライトグリーン' },
    { colorCode: 'H-21', colorName: 'ミドルグリーン' },
    { colorCode: 'H-22', colorName: 'ダークアース' },
    { colorCode: 'H-23', colorName: 'ライトブルー' },
    { colorCode: 'H-24', colorName: 'ダークグレー' },
    { colorCode: 'H-25', colorName: 'ダルレッド' },
    { colorCode: 'H-26', colorName: 'ダルブルー' },
    { colorCode: 'H-27', colorName: 'ダルグリーン' },
    { colorCode: 'H-28', colorName: 'スチールグレー' },
    { colorCode: 'H-29', colorName: 'サーモンピンク' },
    { colorCode: 'H-30', colorName: 'ピンク' },
    { colorCode: 'H-31', colorName: 'ウッドブラウン' },
    { colorCode: 'H-32', colorName: 'タン' },
    { colorCode: 'H-33', colorName: 'ダルオレンジ' },
    { colorCode: 'H-34', colorName: 'スカイグレー' },
    { colorCode: 'H-35', colorName: 'コックピット色(三菱系)' },
    { colorCode: 'H-36', colorName: 'RLM75グレーバイオレット' },
    { colorCode: 'H-37', colorName: 'RLM74グレーグリーン' },
    { colorCode: 'H-38', colorName: 'RLM76ライトブルー' },
    { colorCode: 'H-39', colorName: 'ダークイエロー(2)' },
    { colorCode: 'H-40', colorName: 'ジャーマングレー' },
    { colorCode: 'H-41', colorName: 'レッドブラウン' },
    { colorCode: 'H-42', colorName: 'マホガニー' },
    { colorCode: 'H-43', colorName: 'ウッドブラウン(2)' },
    { colorCode: 'H-44', colorName: 'タン(2)' },
    { colorCode: 'H-45', colorName: 'セールカラー' },
    { colorCode: 'H-46', colorName: 'クリアーオレンジ' },
    { colorCode: 'H-47', colorName: 'クリアーレッド' },
    { colorCode: 'H-48', colorName: 'クリアーブルー' },
    { colorCode: 'H-49', colorName: 'クリアーグリーン' },
    { colorCode: 'H-50', colorName: 'クリアーイエロー' },
    { colorCode: 'H-51', colorName: 'フラットベース' },
    { colorCode: 'H-52', colorName: 'フラットクリアー' },
    { colorCode: 'H-53', colorName: 'クリアー' },
    { colorCode: 'H-54', colorName: 'メタリックブルー' },
    { colorCode: 'H-55', colorName: 'メタリックグリーン' },
    { colorCode: 'H-56', colorName: 'メタリックレッド' },
    { colorCode: 'H-57', colorName: 'メタリックパープル' },
    { colorCode: 'H-58', colorName: 'ウォームホワイト' },
    { colorCode: 'H-59', colorName: 'オレンジイエロー' },
    { colorCode: 'H-60', colorName: 'RLM02グレー' },
    { colorCode: 'H-61', colorName: 'IJAカーキブラウン' },
    { colorCode: 'H-62', colorName: 'オリーブドラブ(2)' },
    { colorCode: 'H-63', colorName: 'ライトグリーン(BS)' },
    { colorCode: 'H-64', colorName: 'ダークグリーン(BS)' },
    { colorCode: 'H-65', colorName: 'ダークグリーン(2)' },
    { colorCode: 'H-66', colorName: 'ライトサンドブラウン' },
    { colorCode: 'H-67', colorName: 'ダークグリーン(3)' },
    { colorCode: 'H-68', colorName: 'ライトグレー' },
    { colorCode: 'H-69', colorName: 'グランプリホワイト' },
    { colorCode: 'H-70', colorName: 'ダークグリーン(陸上自衛隊)' },
    { colorCode: 'H-71', colorName: 'ミドルストーン(BS)' },
    { colorCode: 'H-72', colorName: 'ミドルブルー(BS)' },
    { colorCode: 'H-73', colorName: 'ウォームグレー' },
    { colorCode: 'H-74', colorName: 'エアクラフトグレー' },
    { colorCode: 'H-75', colorName: 'セミグロスブラック' },
    { colorCode: 'H-76', colorName: 'コックピット色(中島系)' },
    { colorCode: 'H-77', colorName: 'ミドルブルー' },
    { colorCode: 'H-78', colorName: 'コックピット色(川西系)' },
    { colorCode: 'H-79', colorName: 'シャインシルバー' },
    { colorCode: 'H-80', colorName: 'コバルトブルー' },
    { colorCode: 'H-81', colorName: 'ライトグレー(ロシア戦車)' },
    { colorCode: 'H-82', colorName: 'オフホワイト(2)' },
    { colorCode: 'H-83', colorName: 'マシンガンカラー' },
    { colorCode: 'H-84', colorName: 'スカイ(BS)' },
    { colorCode: 'H-85', colorName: 'セールカラー(2)' },
    { colorCode: 'H-86', colorName: 'ライトグレー(2)' },
    { colorCode: 'H-87', colorName: 'ゴールドイエロー' },
    { colorCode: 'H-88', colorName: 'ウォームホワイト(2)' },
    { colorCode: 'H-89', colorName: 'ダークイエロー' },
    { colorCode: 'H-90', colorName: 'シャインシルバー(2)' },
  ],
};
