/**
 * Mr.カラー プリセットデータ
 * 将来: 全色追加・公式カラーコード対応
 */
const PRESET_MR_COLOR = {
  maker: 'Mr.カラー',
  series: 'Mr.カラー',
  type: 'lacquer',
  colors: [
    { colorCode: 'C-1',   colorName: 'ホワイト' },
    { colorCode: 'C-2',   colorName: 'ブラック' },
    { colorCode: 'C-3',   colorName: 'レッド' },
    { colorCode: 'C-4',   colorName: 'イエロー' },
    { colorCode: 'C-5',   colorName: 'ブルー' },
    { colorCode: 'C-6',   colorName: 'グリーン' },
    { colorCode: 'C-7',   colorName: 'ブラウン' },
    { colorCode: 'C-8',   colorName: 'シルバー' },
    { colorCode: 'C-9',   colorName: 'ゴールド' },
    { colorCode: 'C-10',  colorName: 'カッパー' },
    { colorCode: 'C-11',  colorName: 'ネービーブルー' },
    { colorCode: 'C-12',  colorName: 'インディブルー' },
    { colorCode: 'C-13',  colorName: 'ニュートラルグレー' },
    { colorCode: 'C-14',  colorName: 'ネービーブルー（2）' },
    { colorCode: 'C-15',  colorName: 'ミドルストーン' },
    { colorCode: 'C-16',  colorName: 'ブラックグリーン' },
    { colorCode: 'C-17',  colorName: 'RLM71ダークグリーン' },
    { colorCode: 'C-18',  colorName: 'RLM70ブラックグリーン' },
    { colorCode: 'C-19',  colorName: 'サンドイエロー' },
    { colorCode: 'C-20',  colorName: 'ライトグリーン' },
    { colorCode: 'C-21',  colorName: 'ミドルグリーン' },
    { colorCode: 'C-22',  colorName: 'ダークアース' },
    { colorCode: 'C-23',  colorName: 'ライトブルー' },
    { colorCode: 'C-25',  colorName: 'ダルレッド' },
    { colorCode: 'C-26',  colorName: 'ダルブルー' },
    { colorCode: 'C-27',  colorName: 'ダルグリーン' },
    { colorCode: 'C-28',  colorName: 'スチールグレー' },
    { colorCode: 'C-29',  colorName: 'サーモンピンク' },
    { colorCode: 'C-30',  colorName: 'ピンク' },
    { colorCode: 'C-31',  colorName: 'ミドルストーン（2）' },
    { colorCode: 'C-32',  colorName: 'ウッドブラウン' },
    { colorCode: 'C-33',  colorName: 'ダルオレンジ' },
    { colorCode: 'C-34',  colorName: 'スカイグレー' },
    { colorCode: 'C-35',  colorName: 'コクピット色（三菱系）' },
    { colorCode: 'C-36',  colorName: 'RLM75グレーバイオレット' },
    { colorCode: 'C-37',  colorName: 'RLM74グレーグリーン' },
    { colorCode: 'C-38',  colorName: 'RLM76ライトブルー' },
    { colorCode: 'C-39',  colorName: 'ダークイエロー(2)' },
    { colorCode: 'C-40',  colorName: 'ジャーマングレー' },
    { colorCode: 'C-41',  colorName: 'レッドブラウン' },
    { colorCode: 'C-42',  colorName: 'マホガニー' },
    { colorCode: 'C-43',  colorName: 'ウッドブラウン(2)' },
    { colorCode: 'C-44',  colorName: 'タン' },
    { colorCode: 'C-45',  colorName: 'セールカラー' },
    { colorCode: 'C-46',  colorName: 'クリアーオレンジ' },
    { colorCode: 'C-47',  colorName: 'クリアーレッド' },
    { colorCode: 'C-48',  colorName: 'クリアーブルー' },
    { colorCode: 'C-49',  colorName: 'クリアーグリーン' },
    { colorCode: 'C-50',  colorName: 'クリアーイエロー' },
    { colorCode: 'C-51',  colorName: 'フラットベース' },
    { colorCode: 'C-52',  colorName: 'フラットクリアー' },
    { colorCode: 'C-53',  colorName: 'クリアー' },
    { colorCode: 'C-54',  colorName: 'メタリックブルー' },
    { colorCode: 'C-55',  colorName: 'メタリックグリーン' },
    { colorCode: 'C-56',  colorName: 'メタリックレッド' },
    { colorCode: 'C-57',  colorName: 'メタリックパープル' },
    { colorCode: 'C-58',  colorName: 'イタリアンレッド' },
    { colorCode: 'C-59',  colorName: 'オレンジイエロー' },
    { colorCode: 'C-60',  colorName: 'RLM02グレー' },
    { colorCode: 'C-61',  colorName: 'IJA カーキブラウン' },
    { colorCode: 'C-62',  colorName: 'オリーブドラブ(2)' },
    { colorCode: 'C-63',  colorName: 'ライトグリーン(BS)' },
    { colorCode: 'C-64',  colorName: 'ダークグリーン(BS)' },
    { colorCode: 'C-65',  colorName: 'ダークグリーン(2)' },
    { colorCode: 'C-66',  colorName: 'ライトサンドブラウン' },
    { colorCode: 'C-67',  colorName: 'ダークグリーン(3)' },
    { colorCode: 'C-68',  colorName: 'ライトグレー' },
    { colorCode: 'C-69',  colorName: 'グランプリホワイト' },
    { colorCode: 'C-70',  colorName: 'ダークグリーン(陸上自衛隊)' },
    { colorCode: 'C-71',  colorName: 'ミドルストーン(BS)' },
    { colorCode: 'C-72',  colorName: 'ミドルブルー(BS)' },
    { colorCode: 'C-73',  colorName: 'ウォームグレー' },
    { colorCode: 'C-74',  colorName: 'エアクラフトグレー' },
    { colorCode: 'C-75',  colorName: 'メカサフ ヘヴィ' },
    { colorCode: 'C-76',  colorName: 'コクピット色(中島系)' },
    { colorCode: 'C-77',  colorName: 'ミドルブルー' },
    { colorCode: 'C-78',  colorName: 'コクピット色(川西系)' },
    { colorCode: 'C-79',  colorName: 'シャインシルバー' },
    { colorCode: 'C-80',  colorName: 'コバルトブルー' },
    { colorCode: 'C-81',  colorName: 'ライトグレー(ロシア戦車)' },
    { colorCode: 'C-82',  colorName: 'オフホワイト' },
    { colorCode: 'C-83',  colorName: 'マシンガンカラー' },
    { colorCode: 'C-84',  colorName: 'スカイ(BS)' },
    { colorCode: 'C-85',  colorName: 'セールカラー(2)' },
    { colorCode: 'C-86',  colorName: 'ライトグレー(2)' },
    { colorCode: 'C-87',  colorName: 'ゴールドイエロー' },
    { colorCode: 'C-88',  colorName: 'ウォームホワイト' },
    { colorCode: 'C-89',  colorName: 'ダークイエロー' },
    { colorCode: 'C-90',  colorName: 'シャインシルバー(2)' },
    { colorCode: 'C-91',  colorName: 'グリーン(陸上自衛隊)' },
    { colorCode: 'C-92',  colorName: 'セミグロスブラック' },
    { colorCode: 'C-93',  colorName: 'ガルグレー' },
    { colorCode: 'C-94',  colorName: 'ライトグレー(アメリカ海軍)' },
    { colorCode: 'C-95',  colorName: 'ライトグレー(陸上自衛隊)' },
    { colorCode: 'C-96',  colorName: 'ライトブラウン' },
    { colorCode: 'C-97',  colorName: 'ライトブルー(2)' },
    { colorCode: 'C-98',  colorName: 'ライトグレーバイオレット' },
    { colorCode: 'C-99',  colorName: 'ダークブルー' },
    { colorCode: 'C-100', colorName: 'マルーン' },
  ],
};
