/**
 * タミヤカラー プリセットデータ（アクリルミニ）
 */
const PRESET_TAMIYA = {
  maker: 'タミヤカラー',
  series: 'アクリルミニ',
  type: 'acrylic',
  colors: [
    { colorCode: 'XF-1',  colorName: 'フラットブラック' },
    { colorCode: 'XF-2',  colorName: 'フラットホワイト' },
    { colorCode: 'XF-3',  colorName: 'フラットイエロー' },
    { colorCode: 'XF-4',  colorName: 'イエローグリーン' },
    { colorCode: 'XF-5',  colorName: 'フラットグリーン' },
    { colorCode: 'XF-6',  colorName: 'コッパー' },
    { colorCode: 'XF-7',  colorName: 'フラットレッド' },
    { colorCode: 'XF-8',  colorName: 'フラットブルー' },
    { colorCode: 'XF-9',  colorName: 'ハルレッド' },
    { colorCode: 'XF-10', colorName: 'フラットブラウン' },
    { colorCode: 'XF-11', colorName: 'J.N.グレイ' },
    { colorCode: 'XF-12', colorName: 'J.N.グリーン' },
    { colorCode: 'XF-13', colorName: 'J.A.グリーン' },
    { colorCode: 'XF-14', colorName: 'J.A.グレー' },
    { colorCode: 'XF-15', colorName: 'フラットフレッシュ' },
    { colorCode: 'XF-16', colorName: 'フラットアルミ' },
    { colorCode: 'XF-17', colorName: 'シーブルー' },
    { colorCode: 'XF-18', colorName: 'ミディアムブルー' },
    { colorCode: 'XF-19', colorName: 'スカイグレイ' },
    { colorCode: 'XF-20', colorName: 'ミディアムグレイ' },
    { colorCode: 'XF-21', colorName: 'スカイ' },
    { colorCode: 'XF-22', colorName: 'RLMグレー' },
    { colorCode: 'XF-23', colorName: 'ライトブルー' },
    { colorCode: 'XF-24', colorName: 'ダークグレー' },
    { colorCode: 'XF-25', colorName: 'ライトシーグレー' },
    { colorCode: 'XF-26', colorName: 'ディープグリーン' },
    { colorCode: 'XF-27', colorName: 'ブラックグリーン' },
    { colorCode: 'XF-28', colorName: 'ダークコッパー' },
    { colorCode: 'XF-29', colorName: 'インディアンレッド' },
    { colorCode: 'XF-30', colorName: 'ダークイエロー2' },
    { colorCode: 'XF-31', colorName: 'ダークグリーン2' },
    { colorCode: 'XF-32', colorName: 'ジャーマングレー' },
    { colorCode: 'XF-33', colorName: 'グレイグリーン' },
    { colorCode: 'XF-34', colorName: 'メタリックブラウン' },
    { colorCode: 'XF-35', colorName: 'フォッケウルフコックピットカラー' },
    { colorCode: 'XF-36', colorName: 'ダークイエロー' },
    { colorCode: 'XF-37', colorName: 'レッドブラウン' },
    { colorCode: 'XF-38', colorName: 'ダークブラウン' },
    { colorCode: 'XF-39', colorName: 'デザートタン' },
    { colorCode: 'XF-40', colorName: 'ジャーマングレー(フラット)' },
    { colorCode: 'XF-41', colorName: 'レッドブラウン2' },
    { colorCode: 'XF-42', colorName: 'マホガニー' },
    { colorCode: 'XF-43', colorName: 'コックピットカラー(三菱系)' },
    { colorCode: 'XF-44', colorName: 'オリーブドラブ1' },
    { colorCode: 'XF-45', colorName: 'フィールドグレー' },
    { colorCode: 'XF-46', colorName: 'ライトグレー' },
    { colorCode: 'XF-47', colorName: 'シーグレー2' },
    { colorCode: 'XF-48', colorName: 'シップグレー' },
    { colorCode: 'XF-49', colorName: 'カーキ' },
    { colorCode: 'XF-50', colorName: 'フィールドブルー' },
    { colorCode: 'XF-51', colorName: 'カーキドラブ' },
    { colorCode: 'XF-52', colorName: 'フラットアース' },
    { colorCode: 'XF-53', colorName: 'ニュートラルグレー' },
    { colorCode: 'XF-54', colorName: 'ダークシーグレー' },
    { colorCode: 'XF-55', colorName: 'デッキタン' },
    { colorCode: 'XF-56', colorName: 'メタリックグレー' },
    { colorCode: 'XF-57', colorName: 'バフ' },
    { colorCode: 'XF-58', colorName: 'オリーブグリーン' },
    { colorCode: 'XF-59', colorName: 'デザートイエロー' },
    { colorCode: 'XF-60', colorName: 'ダークイエロー3' },
    { colorCode: 'XF-61', colorName: 'ダークグリーン3' },
    { colorCode: 'XF-62', colorName: 'オリーブドラブ2' },
    { colorCode: 'XF-63', colorName: 'ジャーマングレー2' },
    { colorCode: 'XF-64', colorName: 'レッドブラウン3' },
    { colorCode: 'XF-65', colorName: 'フィールドグレー2' },
    { colorCode: 'XF-66', colorName: 'ライトグレー2' },
    { colorCode: 'XF-67', colorName: 'NATO グリーン' },
    { colorCode: 'XF-68', colorName: 'NATO ブラウン' },
    { colorCode: 'XF-69', colorName: 'NATO ブラック' },
    { colorCode: 'XF-70', colorName: 'ダークグリーン4' },
    { colorCode: 'XF-71', colorName: 'コックピットカラー(中島系)' },
    { colorCode: 'XF-72', colorName: 'JGSDF ブラウン' },
    { colorCode: 'XF-73', colorName: 'JGSDF カーキ' },
    { colorCode: 'XF-74', colorName: 'JGSDF グリーン' },
    { colorCode: 'XF-75', colorName: 'JGSDF ダークグリーン' },
    { colorCode: 'XF-76', colorName: 'JMSDF グレー' },
    { colorCode: 'XF-77', colorName: 'タイヤブラック' },
    { colorCode: 'XF-78', colorName: 'ウッデンデッキタン' },
    { colorCode: 'XF-79', colorName: 'リネン' },
    { colorCode: 'XF-80', colorName: 'ロイヤルライトグレー' },
    { colorCode: 'XF-81', colorName: 'ダークイエロー(2022)' },
    { colorCode: 'XF-82', colorName: 'オーシャングレー' },
    { colorCode: 'XF-83', colorName: 'メディウムシーグレー' },
    { colorCode: 'XF-84', colorName: 'ダークシーグレー2' },
    { colorCode: 'XF-85', colorName: 'ラバーブラック' },
    { colorCode: 'XF-86', colorName: 'ライトオリーブ' },
    { colorCode: 'XF-87', colorName: 'タスカーグリーン' },
    { colorCode: 'XF-88', colorName: 'ダークイエロー(2)' },
    { colorCode: 'XF-89', colorName: 'ダークグリーン5' },
    { colorCode: 'XF-90', colorName: 'ライトブラウン2' },
    { colorCode: 'XF-91', colorName: 'インダストリアルカーキ' },
    { colorCode: 'XF-92', colorName: 'JASDF ライトグレー' },
    { colorCode: 'X-1',   colorName: 'ブラック' },
    { colorCode: 'X-2',   colorName: 'ホワイト' },
    { colorCode: 'X-3',   colorName: 'ロイヤルブルー' },
    { colorCode: 'X-4',   colorName: 'ブルー' },
    { colorCode: 'X-5',   colorName: 'グリーン' },
    { colorCode: 'X-6',   colorName: 'オレンジ' },
    { colorCode: 'X-7',   colorName: 'レッド' },
    { colorCode: 'X-8',   colorName: 'レモンイエロー' },
    { colorCode: 'X-9',   colorName: 'バフ' },
    { colorCode: 'X-10',  colorName: 'ガンメタル' },
    { colorCode: 'X-11',  colorName: 'クロームシルバー' },
    { colorCode: 'X-12',  colorName: 'ゴールドリーフ' },
    { colorCode: 'X-13',  colorName: 'メタリックブルー' },
    { colorCode: 'X-14',  colorName: 'スカイブルー' },
    { colorCode: 'X-15',  colorName: 'ライトグリーン' },
    { colorCode: 'X-16',  colorName: 'パープル' },
    { colorCode: 'X-17',  colorName: 'ピンク' },
    { colorCode: 'X-18',  colorName: 'セミグロスブラック' },
    { colorCode: 'X-19',  colorName: 'スモーク' },
    { colorCode: 'X-20A', colorName: 'アクリル溶剤' },
    { colorCode: 'X-21',  colorName: 'フラットベース' },
    { colorCode: 'X-22',  colorName: 'クリアー' },
    { colorCode: 'X-23',  colorName: 'クリアーブルー' },
    { colorCode: 'X-24',  colorName: 'クリアーイエロー' },
    { colorCode: 'X-25',  colorName: 'クリアーグリーン' },
    { colorCode: 'X-26',  colorName: 'クリアーオレンジ' },
    { colorCode: 'X-27',  colorName: 'クリアーレッド' },
    { colorCode: 'X-28',  colorName: 'パークシーン' },
  ],
};
